#!/usr/bin/env bash
# Copyright 2018, Irfan Sharif.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
if [ ! -f run-container ]; then
  echo 'ERR: run-container must be run from irfansharif/notebooks root dir' 1>&2
  exit 1
fi

docker run -it \
  -p 8888:8888 \
  --mount type=bind,source="$PWD"/src,target=/notebooks \
  irfansharif/notebooks
