#!/usr/bin/env bash
# Copyright 2018, Irfan Sharif.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
if [ ! -f scripts/build-container ]; then
  echo 'ERR: build-container must be run from irfansharif/notebooks root (using scripts/build-container)' 1>&2
  exit 1
fi

function print_usage() {
  echo "scripts/build-container: Builds the notebook container images (image with packaged notebooks only, by default)"
  echo
  echo "Usage: scripts/build-container [options]";
  echo
  echo "  Options:"
  echo "    -h, --help   Show this screen."
  echo "    -b, --base   Build the base container image."
  echo "    --all        Builds both container images."
}

# Default mode: we run the notebook container.
MODE='notebook'

while test $# -gt 0
do
    case "$1" in
        --base|-b)
              MODE='notebook-base'
            ;;
        --all)
              MODE='all'
            ;;
        --help|-h)
              MODE='help'
            ;;
        --*|-*|*)
              MODE='incorrect-usage'
            ;;
    esac
    shift
done

case "$MODE" in
  notebook)
      docker build -q \
        -t irfansharif/notebooks \
        -f Dockerfile .
      echo "INFO: Built irfansharif/notebooks"
    ;;

  notebook-base)
      docker build -q \
        -t irfansharif/notebooks-base \
        -f Dockerfile.base .
      echo "INFO: Built irfansharif/notebooks-base"
    ;;

  all)
      docker build -q \
        -t irfansharif/notebooks \
        -f Dockerfile .
      echo "INFO: Built irfansharif/notebooks"
      echo

      docker build -q \
        -t irfansharif/notebooks-base \
        -f Dockerfile.base .
      echo "INFO: Built irfansharif/notebooks-base"
    ;;

  help)
      print_usage
    ;;

  incorrect-usage)
      print_usage
      exit 1
    ;;
esac
