#!/usr/bin/env bash
# Copyright 2018, Irfan Sharif.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
if [ ! -f scripts/run-container ]; then
  echo 'ERR: run-container must be run from irfansharif/notebooks root (using scripts/run-container)' 1>&2
  exit 1
fi

function print_usage() {
  echo "scripts/run-container: Runs the notebook container images (image with packaged notebooks by default)"
  echo
  echo "Usage: scripts/run-container [options]";
  echo
  echo "  Options:"
  echo "    -h --help:   Show this screen."
  echo "    -b --base:   Run the base container image."
}

# Default mode: we run the notebook container.
MODE='notebook'

while test $# -gt 0
do
    case "$1" in
        --base)
              MODE='notebook-base'
            ;;
        --help|-h)
              MODE='help'
            ;;
        --*|-*|*)
              MODE='incorrect-usage'
            ;;
    esac
    shift
done

case "$MODE" in
  notebook)
      docker run -it --rm \
        -p 8888:8888 \
        --mount type=bind,source="$PWD"/notebooks,target=/notebooks \
        irfansharif/notebooks
    ;;
  notebook-base)
      docker run -it --rm \
        -p 8888:8888 \
        irfansharif/notebooks-base
    ;;
  help)
      print_usage
    ;;
  incorrect-usage)
      print_usage
      exit 1
    ;;
esac
